In [1]:
# Enable inline plotting in Jupyter notebook
%matplotlib inline
# Import numerical computing library
import numpy as np
# Import image processing functions
from scipy import ndimage
# Import signal processing functions (including convolution)
from scipy import signal
# Import plotting library
import matplotlib.pyplot as plt

In [2]:
# Load an image file named 'Tesla.png' into a numpy array
# The image is stored in RGB format with shape (height, width, 3)
I = plt.imread('Tesla.png')

# Print the shape and data type of the loaded image
print(f"Image shape: {I.shape}")
print(f"Image data type: {I.dtype}")
print(f"Pixel value range: {I.min()} to {I.max()}")

Image shape: (473, 784, 3)
Image data type: float32
Pixel value range: 0.0 to 1.0


In [3]:
# Create a figure with a specific size (16x9 inches) for better visualization
fig = plt.figure(figsize=(16,9))
# Display the original color image
plt.imshow(I)
# Add a title to the plot
plt.title('Original Color Image')
# Add axis labels
plt.xlabel('Width (pixels)')
plt.ylabel('Height (pixels)')
# Show the colorbar to understand pixel intensity values
plt.colorbar(label='Pixel Intensity')

In [4]:
# Convert RGB image to grayscale using the standard luminance formula
def rgb2gray(rgb):
    """
    Convert an RGB image to grayscale using the standard luminance formula.
    The weights (0.2989, 0.5870, 0.1140) approximate human perception of color brightness.
    """
    # Extract RGB channels
    r, g, b = rgb[:,:,0], rgb[:,:,1], rgb[:,:,2]
    # Apply luminance formula: 0.2989*R + 0.5870*G + 0.1140*B
    gray = 0.2989 * r + 0.5870 * g + 0.1140 * b
    return gray

# Convert the loaded image to grayscale
Ig = rgb2gray(I)

# Display the grayscale image with a grayscale colormap
fig = plt.figure(figsize=(16,9))
plt.imshow(Ig, cmap=plt.cm.gray)
plt.title('Grayscale Image')
plt.axis('off')  # Hide axis for better visualization

(-0.5, 783.5, 472.5, -0.5)

In [5]:
# Define a convolution kernel (filter)
# This is a Sobel kernel for edge detection in the horizontal direction
# It highlights vertical edges in the image
k = np.array([
    [ 1,  2,  1],  # Weights for the top row of the kernel
    [ 0,  0,  0],  # Middle row (no contribution to the result)
    [-1, -2, -1]   # Weights for the bottom row (negative to detect edges)
])

# Transpose the kernel to make it detect horizontal edges instead of vertical
# This is equivalent to rotating the kernel 90 degrees counter-clockwise
k = np.transpose(k)

# Alternative: Uncomment to use a simple averaging filter instead
# k = np.ones((11,11)) * (1/(11**2))  # 11x11 averaging filter

In [6]:
print(k)

[[ 1  0 -1]
 [ 2  0 -2]
 [ 1  0 -1]]


In [7]:
# Apply 2D convolution to the grayscale image using the defined kernel
# signal.convolve2d performs a 2-dimensional convolution operation
# The 'same' mode ensures the output has the same dimensions as the input
If = signal.convolve2d(Ig, k, mode='same')

# Create a figure for displaying the filtered image
fig = plt.figure(figsize=(16,9))

# Display the convolved image in grayscale
# The 'gray' colormap is used to represent the filtered intensities
plt.imshow(If, cmap=plt.cm.gray)

# Add title and labels for better understanding
plt.title('Filtered Image (Edge Detection)')
plt.xlabel('Width (pixels)')
plt.ylabel('Height (pixels)')
plt.colorbar(label='Edge Strength')

# The resulting image (If) will show edges where there are rapid intensity changes
# in the direction perpendicular to the kernel's orientation